server:
  port: 8086

spring:
  application:
    name: recommendation-service

jwt:
  secret: ${JWT_SECRET}

journal:
  service:
    url: ${JOURNAL_SERVICE_URL:http://journal-service:8083}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-server:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
